### ISSUE TITLE
zeek-files-labeler.py does not work for x509.log

### ISSUE THREAD

**Issue by MariaRigaki** [stratosphereips/netflowlabeler#3]
The script empties the contents of the `x509.log` file. Most probably because the `x509.log` uses a different identifier that references the `ssl.log` and not the `conn.log`.

The easiest approach would be to just avoid labeling the x509.log.

**Comment by MariaRigaki** [comment]
The same thing happens with the `files.log`

**Comment by eldraco** [comment]
Thanks for reporting. It is solved now. Try latest version.
